COMMON: &common
  HOST: 127.0.0.1
  BAR_FORMAT: "{desc:<10}{percentage:3.0f}%|{bar:25}{r_bar}{bar:-10b}"

NSE:
  <<: *common # add the common configuration
  PORT: 3000
  PAPER: 3001 # For paper trades in IBG
  EXCHANGE: 'NSE'
  CURRENCY: 'INR'

  CALLSTDMULT: 1.95 # Min stdev multiple for calls
  PUTSTDMULT: 1.9 # Min stdev multiple for puts
  MINEXPROM: 1.55 # Minimum expected return on margin
  MINOPTSELLPRICE: 0.2 # Minimum option selling price

  PREC: 0.05 # For Option trade price